spring.application.name=startup-intelligence-api
spring.datasource.url=jdbc:postgresql://localhost:5432/startup_database
spring.datasource.username=postgres
spring.datasource.password=sasiadmin

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true